config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "/tasks", to:"tasks#index"

  get "tasks/new", to: "tasks#new", as: "tasknew"

  get "tasks/:id", to:"tasks#show", as:"task"

  post "/tasks", to: "tasks#create"

  get "tasks/:id/edit", to: "tasks#edit", as:"taskedit"

  patch "tasks/:id", to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy"

 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @tasks = Task.new
  end

  def show
    @tasks = Task.find(params[:id])
  end

  def create
    @tasks = Task.new (task_params)
    @tasks.save
    redirect_to task_path(@tasks)
  end

  def edit
    @tasks = Task.find(params[:id])
  end

  def update
    @tasks = Task.find(params[:id])
    @tasks.update(task_params)
    redirect_to task_path(@tasks)
  end

  def destroy
    @tasks = Task.find(params[:id])
    @tasks.destroy
    redirect_to tasks_path
  end

end


private

def task_params
  params.require(:task).permit(:title, :details, :completed)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>


<%= form_for @tasks do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.label :completed%>
    <%= f.check_box :completed %>
  <%= f.submit %>
<%end %>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
      <li>
        <%= check_box_tag "tasks_ids[]", task.id, task.completed, disabled: true %>
        <%= link_to task.title, task_path(task) %>
        <%= link_to 'Remove', tasks_path , method: :delete %>
      </li>
  <% end %>
</ul>

<%= link_to "+ Add new task", tasknew_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_for @tasks do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :details %>
    <%= f.text_field :details %>

   <p>
      <%= f.label :completed %>
      <%= f.check_box :completed, {}, true, false %>
   </p>

  <%= f.submit %>
<%end %>

<%= link_to "back to list", tasks_path %>

app/views/tasks/show.html.erb
<h2><%= @tasks.title %></h2>
<p><%= @tasks.details %></p>


<p><%= link_to"Edit", taskedit_path %></p>
<p><%= link_to "back to list", tasks_path %></p>